### ISSUE TITLE
Error retrieving the response of a batch from mailchimp

### ISSUE THREAD

**Issue by xeontcs** [mailchimp/mc-magento2#1204]
Magento 2.4.2
PHP 7.4.18
MailChimp latest version installed  "version": "103.4.43",

In the  MalChimp.log we have,

[2021-06-04 03:40:08] MailChimpLogger.INFO: Deprecated Functionality: Invalid characters passed for attempted conversion, these have been ignored in /var/www/vhosts/domain.tld/httpdocs/vendor/magento/framework/Archive/Tar.php on line 450
 [] []
[2021-06-04 03:40:08] MailChimpLogger.INFO: Error with a response: The "/var/www/vhosts/domain.tld/httpdocs/var/Mailchimp/a5720fbc2b//var/www/vhosts/domain.tld/httpdocs/var/Mailchimp/a5720fbc2b/6a65c4980c.json" file can't be deleted. Warning!unlink(/var/www/vhosts/domain.tld/httpdocs/var/Mailchimp/a5720fbc2b//var/www/vhosts/domain.tld/httpdocs/var/Mailchimp/a5720fbc2b/6a65c4980c.json): No such file or directory
 [] []
[2021-06-04 03:40:11] MailChimpLogger.INFO: Deprecated Functionality: Invalid characters passed for attempted conversion, these have been ignored in /var/www/vhosts/domain.tld/httpdocs/vendor/magento/framework/Archive/Tar.php on line 450
 [] []
[2021-06-04 03:40:11] MailChimpLogger.INFO: Error with a response: The "/var/www/vhosts/domain.tld/httpdocs/var/Mailchimp/058707bd1c//var/www/vhosts/domain.tld/httpdocs/var/Mailchimp/058707bd1c/058707bd1c.tar" file can't be deleted. Warning!unlink(/var/www/vhosts/domain.tld/httpdocs/var/Mailchimp/058707bd1c//var/www/vhosts/domain.tld/httpdocs/var/Mailchimp/058707bd1c/058707bd1c.tar): No such file or directory
 [] []
[2021-06-04 03:40:11] MailChimpLogger.INFO: Generate Products payload
 [] []
[2021-06-04 03:40:11] MailChimpLogger.INFO: Generate Customers payload
 [] []
[2021-06-04 03:40:11] MailChimpLogger.INFO: Generate Orders payload
 [] []
[2021-06-04 03:40:11] MailChimpLogger.INFO: Generate Carts payload
 [] []
[2021-06-04 03:40:11] MailChimpLogger.INFO: Generate Rules payload
 [] []
[2021-06-04 03:40:11] MailChimpLogger.INFO: Generate Coupons payload
 [] []
[2021-06-04 03:40:12] MailChimpLogger.INFO: Sent batch 44652e445e for store 1
 [] []
[2021-06-04 03:40:12] MailChimpLogger.INFO: {
    "CustomerModified": 1
}
 [] []

What could be causing this issue?

Thank you.

**Comment by wahidnory** [comment]
Not sure if this one is fixed, we are still experiencing this on magento 2.4.2. php version 7.4
It seems that it's triggered during the cron job.

```
ErrorException: Deprecated: Invalid characters passed for attempted conversion, these have been ignored
#33 /releases/20211005115526/vendor/magento/framework/Archive/Tar.php(450): Magento\Framework\Archive\Tar::_extractFileHeader
#32 /releases/20211005115526/vendor/magento/framework/Archive/Tar.php(392): Magento\Framework\Archive\Tar::_unpackCurrentTar
#31 /releases/20211005115526/vendor/magento/framework/Archive/Tar.php(551): Magento\Framework\Archive\Tar::unpack
#30 /releases/20211005115526/vendor/magento/framework/Archive.php(143): Magento\Framework\Archive::unpack
#29 /releases/20211005115526/vendor/mailchimp/mc-magento2/Model/Api/Result.php(155): Ebizmarts\MailChimp\Model\Api\Result::getBatchResponse
#28 /releases/20211005115526/vendor/mailchimp/mc-magento2/Model/Api/Result.php(82): Ebizmarts\MailChimp\Model\Api\Result::processResponses
#27 /releases/20211005115526/vendor/mailchimp/mc-magento2/Cron/Ecommerce.php(141): Ebizmarts\MailChimp\Cron\Ecommerce::execute
#26 [internal](0): call_user_func_array
#25 /releases/20211005115526/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(355): Magento\Cron\Observer\ProcessCronQueueObserver::_runJob
#24 /releases/20211005115526/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(829): Magento\Cron\Observer\ProcessCronQueueObserver::tryRunJob
#23 /releases/20211005115526/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(796): Magento\Cron\Observer\ProcessCronQueueObserver::processPendingJobs
#22 /releases/20211005115526/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(272): Magento\Cron\Observer\ProcessCronQueueObserver::execute
#21 /releases/20211005115526/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor::___callParent
#20 /releases/20211005115526/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor::Magento\Framework\Interception\{closure}
#19 /releases/20211005115526/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor::___callPlugins
#18 /Magento/Cron/Observer/ProcessCronQueueObserver/Interceptor.php(23): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor::execute
#17 /releases/20211005115526/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Framework\Event\Invoker\InvokerDefault::_callObserverMethod
#16 /releases/20211005115526/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault::dispatch
#15 /releases/20211005115526/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Manager::dispatch
```

This is with the latest version: 103.4.44
