### ISSUE TITLE
Adding duplicates to collection with join 

### ISSUE THREAD

**Issue by brideo** [mailchimp/mc-magento2#1684]
Mailchimp does some joins without a group, then Magento throws an error because we are trying to add the same ID to a collection twice.

```
Fatal error: Uncaught Exception: Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "50192" already exists. in /var/www/releases/2983/vendor/magento/framework/Data/Collection.php:407
Stack trace:
#0 /var/www/releases/2983/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php(315): Magento\Framework\Data\Collection->addItem(Object(Magento\Catalog\Model\Product\Interceptor))
#1 /var/www/releases/2983/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php(1142): Magento\Eav\Model\Entity\Collection\AbstractCollection->addItem(Object(Magento\Catalog\Model\Product\Interceptor))
#2 /var/www/releases/2983/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php(930): Magento\Eav\Model\Entity\Collection\AbstractCollection->_loadEntities(false, false)
#3 /var/www/releases/2983/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php(801): Magento\Eav\Model\Entity\Collection\AbstractCollection->load(false, false)
#4 /var/www/releases/2983/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product\Collection->load(false, false)
#5 /var/www/releases/2983/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor->___callParent('load', Array)
#6 /var/www/releases/2983/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor->Magento\Framework\Interception\{closure}()
#7 /var/www/releases/2983/generated/code/Magento/Catalog/Model/ResourceModel/Product/Collection/Interceptor.php(23): Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor->___callPlugins('load', Array, Array)
#8 /var/www/releases/2983/vendor/magento/framework/Data/Collection.php(840): Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor->load()
#9 /var/www/releases/2983/vendor/mailchimp/mc-magento2/Model/Api/Product.php(143): Magento\Framework\Data\Collection->getIterator()
#10 /var/www/releases/2983/vendor/mailchimp/mc-magento2/Cron/Ecommerce.php(212): Ebizmarts\MailChimp\Model\Api\Product->_sendProducts(1)
#11 /var/www/releases/2983/vendor/mailchimp/mc-magento2/Cron/Ecommerce.php(142): Ebizmarts\MailChimp\Cron\Ecommerce->_processStore(1, '123.', '123')
#12 /var/www/releases/2983/app/code/CustomModule/MailChimp/Cron/Ecommerce.php(29): Ebizmarts\MailChimp\Cron\Ecommerce->execute()
#13 /var/www/releases/2983/bin/cron/mailchimp.php/meta.php(18): CustomModule\MailChimp\Cron\Ecommerce->execute()
#14 {main}
  thrown in /var/www/releases/2983/vendor/magento/framework/Data/Collection.php on line 407
```

You should add group by's to prevent this: 

```
$collection->getSelect()->limit(self::MAX);
$collection->getSelect()->group('entity_id')->limit(self::MAX);
```

Here is my composer patch: 

```
diff --git a/Model/Api/Cart.php b/Model/Api/Cart.php
index 318e321..96b54a8 100644
--- a/Model/Api/Cart.php
+++ b/Model/Api/Cart.php
@@ -157,7 +157,7 @@ class Cart
         // be sure that the quotes are already in mailchimp and not deleted
         $convertedCarts->getSelect()->where("m4m.mailchimp_sync_deleted = 0 and m4m.related_id is not null");
         // limit the collection
-        $convertedCarts->getSelect()->limit(self::BATCH_LIMIT);
+        $convertedCarts->getSelect()->group('entity_id')->limit(self::BATCH_LIMIT);
         /**
          * @var $cart \Magento\Quote\Model\Quote
          */
@@ -239,6 +239,7 @@ class Cart
         );
         // limit the collection
         $modifiedCarts->getSelect()->limit(self::BATCH_LIMIT);
+        $modifiedCarts->getSelect()->group('main_table.entity_id');

         /**
          * @var $cart \Magento\Quote\Model\Quote
@@ -371,6 +372,7 @@ class Cart

         // limit the collection
         $newCarts->getSelect()->limit(self::BATCH_LIMIT);
+        $newCarts->getSelect()->group('main_table.entity_id');
         /**
          * @var $cart \Magento\Quote\Model\Quote
          */
@@ -498,6 +500,7 @@ class Cart
         );
         // be sure that the quotes are already in mailchimp and not deleted
         $allCartsForEmail->getSelect()->where("m4m.mailchimp_sync_deleted = 0");
+        $allCartsForEmail->getSelect()->group('main_table.entity_id');
         return $allCartsForEmail;
     }

diff --git a/Model/Api/Product.php b/Model/Api/Product.php
index 410d76d..495e3f9 100644
--- a/Model/Api/Product.php
+++ b/Model/Api/Product.php
@@ -139,7 +139,7 @@ class Product
         $collection->getSelect()->where("m4m.mailchimp_sync_delta IS null OR (m4m.mailchimp_sync_delta > '".
             $this->_helper->getMCMinSyncDateFlag().
             "' and m4m.mailchimp_sync_modified = 1)");
-        $collection->getSelect()->limit(self::MAX);
+        $collection->getSelect()->group('e.entity_id')->limit(self::MAX);
         foreach ($collection as $item) {
             /**
              * @var $product \Magento\Catalog\Model\Product

```

**Comment by gonzaloebiz** [comment]
Hi @brideo 

please follow the [Issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best

**Comment by gonzaloebiz** [comment]
Hi @brideo 

no news in one week, close the issue until you follow the [Issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best
