### ISSUE TITLE
Error while update mc-magento2 from 1.0.30 to 1.0.32 by Composer in Magento CE 2.1.9

### ISSUE THREAD

**Issue by aboutzahurul** [mailchimp/mc-magento2#559]
We are getting this error on our production mirror site while trying to update. Then we try after setup fresh Magento CE 2.1.9 with sample data still getting the error.

### Preconditions
1. Magento CE 2.1.9 with sample data
2. mc-magento2 1.0.30 installed by composer

### Steps to reproduce
1. Update mc-magento2 1.0.30 to 1.0.32 by composer
2. Run magento upgrade command `php bin/magento setup:upgrade;`
3. or Run magento compile command `php bin/magento setup:di:compile;`
4. or try visit/load the website

### Expected result
magento Upgrade or Compile command should execute normally. or website should working normally

### Actual result
magento Upgrade or Compile command give error below:
```
  [ReflectionException]
  Class Magento\Framework\Serialize\Serializer\Json does not exist
```
```
  [ReflectionException]
  Class Magento\Framework\Serialize\Serializer\Json does not exist
```
![image](https://user-images.githubusercontent.com/2784405/51431521-2c71d900-1c54-11e9-930e-1734e2c929ca.png)

Also Website dont load, its give you Error log record number. if you check the Error log record number, you see error like below:
```
a:4:{i:0;s:209:"Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Ebizmarts_MailChimp data: current version - 1.0.30, required version - 1.0.32";i:1;s:2546:"#0 /home/user/public_html/test/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#1 /home/user/public_html/test/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#2 /home/user/public_html/test/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#3 /home/user/public_html/test/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#4 /home/user/public_html/test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#5 /home/user/public_html/test/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#6 /home/user/public_html/test/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#7 /home/user/public_html/test/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#8 /home/user/public_html/test/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /home/user/public_html/test/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#10 /home/user/public_html/test/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#11 {main}";s:3:"url";s:6:"/test/";s:11:"script_name";s:15:"/test/index.php";}
```

**Comment by gonzaloebiz** [comment]
Please see at https://github.com/mailchimp/mc-magento2/issues/473

**Comment by aboutzahurul** [comment]
> you can install any branch with
> 
> composer require mailchimp/mc-magento2:dev-develop-2.2
> 
> you can use : to specify the branch
> 
> Best
> 
https://github.com/mailchimp/mc-magento2/issues/473#issuecomment-453129047

@gonzaloebiz Do you suggest us to install develop version on our production server? Please explain a bit how to solve it. Thanks

**Comment by gonzaloebiz** [comment]
We are testing the develop version to release a new version soon, so i think the better is to wait for this new release.

Best
