### ISSUE TITLE
Unable to set production mode

### ISSUE THREAD

**Issue by evilprophet** [mailchimp/mc-magento2#64]
1. Magento CE 2.1.7
2. mc-magento2 1.0.22.

### Steps to reproduce:
bin/magento deploy:mode:set production

### Expected result:
Magento should be switched to production mode
### Actual result:
Now error in setup:di:compile:

`bin/magento deploy:mode:set production -vvv
Enabled maintenance mode
Starting compilation
Something went wrong while compiling generated code. See the error log for details.
Command returned non-zero exit code:
`/usr/bin/php -f /var/www/m2c/bin/magento setup:di:compile`
#0 /var/www/m2c/vendor/magento/module-deploy/Model/Filesystem.php(245): Magento\Framework\App\Shell->execute('/usr/bin/php -f...')
#1 /var/www/m2c/vendor/magento/module-deploy/Model/Filesystem.php(143): Magento\Deploy\Model\Filesystem->compile(Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/m2c/vendor/magento/module-deploy/Model/Mode.php(83): Magento\Deploy\Model\Filesystem->regenerateStatic(Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/m2c/vendor/magento/module-deploy/Console/Command/SetModeCommand.php(100): Magento\Deploy\Model\Mode->enableProductionMode()
#4 /var/www/m2c/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Magento\Deploy\Console\Command\SetModeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/m2c/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/m2c/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Deploy\Console\Command\SetModeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/m2c/vendor/magento/framework/Console/Cli.php(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/m2c/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/m2c/bin/magento(23): Symfony\Component\Console\Application->run()
#10 {main}`

### Additional information:
I think that magento doesn't know what is `ebizmarts/mailchimp-lib` maybe if you add 
something like in registration.php this will be work:
```\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::LIBRARY,
    ebizmarts/mailchimp-lib',
    __DIR__ . '../../ebizmarts/mailchimp-lib'
);

**Comment by gonzaloebiz** [comment]
Hi @evilprophet 

what method you use to install the extension?

**Comment by jordanbrauer** [comment]
I am able to use put my store in production mode.

It seems that you used the downloaded `.zip` installation method, no?

If so, you have to install `mailchimp-lib` separately by executing `composer require ebizmarts/mailchimp-lib` in your project root.

@gonzaloebiz I think it would be worth updating the `.zip` file download 🤔 – I see this issue pop up often when I google around for information. Thoughts?

**Comment by evilprophet** [comment]
I used composer

**Comment by gonzaloebiz** [comment]
@evilprophet 

sorry, but why you think that the error comes from mailchimp-lib? I don't see any message related to mailchimp-lib

**Comment by evilprophet** [comment]
@gonzaloebiz 
I thinkt that sometimes I had similar issue when I tried use external lib

**Comment by gonzaloebiz** [comment]
If you install the external libs with composer, you don't need any registration.
I understand your experiences, but as per your log, is nothing related to mailchimp-lib.
Please, try in a vanilla installation, and install the extension via composer.

I close the issue for now, look like your issue is not related to mc-magento2

Best

**Comment by evilprophet** [comment]
This was a vanilla instalation...
I didn't modify your extension this was only a suggestion

**Comment by gonzaloebiz** [comment]
Please, run

composer info

and paste the result

**Comment by evilprophet** [comment]
Production mode now is not important, maybe something in my side but after instalation this extension on dev environment I have strange error after setup:upgrade.
Do you know something about it?

```Module 'Ebizmarts_MailChimp':



  [Magento\Framework\Exception\LocalizedException]
  Invalid entity_type specified: customer



Exception trace:
 () at /var/www/html/vendor/magento/module-eav/Model/Config.php:350
 Magento\Eav\Model\Config->getEntityType() at /var/www/html/vendor/magento/module-eav/Model/Entity/AbstractEntity.php:296
 Magento\Eav\Model\Entity\AbstractEntity->setType() at /var/www/html/var/generation/Magento/Customer/Model/ResourceModel/Customer/Interceptor.php:180
 Magento\Customer\Model\ResourceModel\Customer\Interceptor->setType() at /var/www/html/vendor/magento/module-customer/Model/ResourceModel/Customer.php:71
 Magento\Customer\Model\ResourceModel\Customer->__construct() at /var/www/html/var/generation/Magento/Customer/Model/ResourceModel/Customer/Interceptor.php:14
 Magento\Customer\Model\ResourceModel\Customer\Interceptor->__construct() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:89
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php:57
 Magento\Framework\ObjectManager\ObjectManager->create() at /var/www/html/setup/src/Magento/Setup/Model/Installer.php:931
 Magento\Setup\Model\Installer->createSchemaDataHandler() at /var/www/html/setup/src/Magento/Setup/Model/Installer.php:1245
 Magento\Setup\Model\Installer->getSchemaDataHandler() at /var/www/html/setup/src/Magento/Setup/Model/Installer.php:841
 Magento\Setup\Model\Installer->handleDBSchemaData() at /var/www/html/setup/src/Magento/Setup/Model/Installer.php:779
 Magento\Setup\Model\Installer->installSchema() at n/a:n/a
 call_user_func_array() at /var/www/html/setup/src/Magento/Setup/Model/Installer.php:344
 Magento\Setup\Model\Installer->install() at /var/www/html/setup/src/Magento/Setup/Console/Command/InstallCommand.php:125
 Magento\Setup\Console\Command\InstallCommand->execute() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/magento/framework/Console/Cli.php:96
 Magento\Framework\Console\Cli->doRun() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/www/html/bin/magento:23


setup:install [--backend-frontname="..."] [--key="..."] [--session-save="..."] [--definition-format="..."] [--db-host="..."] [--db-name="..."] [--db-user="..."] [--db-engine="..."] [--db-password="..."] [--db-prefix="..."] [--db-model="..."] [--db-init-statements="..."] [-s|--skip-db-validation] [--http-cache-hosts="..."] [--base-url="..."] [--language="..."] [--timezone="..."] [--currency="..."] [--use-rewrites="..."] [--use-secure="..."] [--base-url-secure="..."] [--use-secure-admin="..."] [--admin-use-security-key="..."] [--admin-user="..."] [--admin-password="..."] [--admin-email="..."] [--admin-firstname="..."] [--admin-lastname="..."] [--cleanup-database] [--sales-order-increment-prefix="..."] [--use-sample-data] [--magento-init-params="..."]

 in /var/www/html/vendor/magento/framework/Shell.php:61
Stack trace:
#0 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Application.php(462): Magento\Framework\Shell->execute('/usr/bin/php -f...', Array)
#1 /var/www/html/dev/tests/integration/framework/bootstrap.php(68): Magento\TestFramework\Application->install()
#2 /var/www/html/vendor/phpunit/phpunit/src/Util/Fileloader.php(93): include_once('/var/www/html/d...')
#3 /var/www/html/vendor/phpunit/phpunit/src/Util/Fileloader.php(77): PHPUnit_Util_Fileloader::load('/var/www/html/d...')
#4 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(806): PHPUnit_Util_Fileloader::checkAndLoad('/var/www/html/b...')
#5 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(636): PHPUnit_TextUI_Command->handleBootstrap('/var/www/html/b...')
#6 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit_TextUI_Command->handleArguments(Array)
#7 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(132): PHPUnit_TextUI_Command->run(Array, true)
#8 /var/www/html/vendor/phpunit/phpunit/phpunit(55): PHPUnit_TextUI_Command::main()
#9 {main}

Next Magento\Framework\Exception\LocalizedException: Command returned non-zero exit code:
`/usr/bin/php -f '/var/www/html/bin/magento' setup:install -vvv --db-host='127.0.0.1' --db-user='root' --db-name='magento2_integration_tests' --backend-frontname='backend' --admin-user='user' --admin-password='password1' --admin-email='admin@example.com' --admin-firstname='firstname' --admin-lastname='lastname' --magento-init-params='MAGE_DIRS[etc][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-810245534ede1b604ef6316670ac555f/etc&MAGE_DIRS[var][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-810245534ede1b604ef6316670ac555f/var&MAGE_DIRS[media][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-810245534ede1b604ef6316670ac555f/pub/media&MAGE_DIRS[static][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-810245534ede1b604ef6316670ac555f/pub/static&MAGE_DIRS[generation][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-810245534ede1b604ef6316670ac555f/var/generation&MAGE_DIRS[cache][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-810245534ede1b604ef6316670ac555f/var/cache&MAGE_DIRS[log][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-810245534ede1b604ef6316670ac555f/var/log&MAGE_DIRS[session][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-810245534ede1b604ef6316670ac555f/var/session&MAGE_DIRS[tmp][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-810245534ede1b604ef6316670ac555f/var/tmp&MAGE_DIRS[upload][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-810245534ede1b604ef6316670ac555f/var/upload&MAGE_DIRS[pub][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-810245534ede1b604ef6316670ac555f/pub&MAGE_MODE=developer' 2>&1` in /var/www/html/vendor/magento/framework/Shell.php:62
Stack trace:
#0 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Application.php(462): Magento\Framework\Shell->execute('/usr/bin/php -f...', Array)
#1 /var/www/html/dev/tests/integration/framework/bootstrap.php(68): Magento\TestFramework\Application->install()
#2 /var/www/html/vendor/phpunit/phpunit/src/Util/Fileloader.php(93): include_once('/var/www/html/d...')
#3 /var/www/html/vendor/phpunit/phpunit/src/Util/Fileloader.php(77): PHPUnit_Util_Fileloader::load('/var/www/html/d...')
#4 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(806): PHPUnit_Util_Fileloader::checkAndLoad('/var/www/html/b...')
#5 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(636): PHPUnit_TextUI_Command->handleBootstrap('/var/www/html/b...')
#6 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit_TextUI_Command->handleArguments(Array)
#7 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(132): PHPUnit_TextUI_Command->run(Array, true)
#8 /var/www/html/vendor/phpunit/phpunit/phpunit(55): PHPUnit_TextUI_Command::main()
#9 {main}

**Comment by gonzaloebiz** [comment]
Hi @evilprophet 

please, don't post other issues not related to the original.
By the way, i don't see any related to us in your last post

Best
