### ISSUE TITLE
Exception "Unable to unserialize value"

### ISSUE THREAD

**Issue by ktsixit** [mailchimp/mc-magento2#662]
## Issue Description
In customer account menu (frontend), when clicking on 'My Newsletter Subscriptions' menu, I'm getting error 
```
1 exception(s):
Exception #0 (InvalidArgumentException): Unable to unserialize value.

Exception #0 (InvalidArgumentException): Unable to unserialize value.
#0 /home/myserver/public_html/clients/mywebsite/vendor/mailchimp/mc-magento2/Helper/Data.php(1028): Magento\Framework\Serialize\Serializer\Json->unserialize(NULL)
#1 /home/myserver/public_html/clients/mywebsite/vendor/mailchimp/mc-magento2/Block/Newsletter.php(58): Ebizmarts\MailChimp\Helper\Data->getSubscriberInterest(NULL, NULL)
#2 /home/myserver/public_html/clients/mywebsite/generated/code/Ebizmarts/MailChimp/Block/Newsletter/Interceptor.php(24): Ebizmarts\MailChimp\Block\Newsletter->getInterest()
#3 /home/myserver/public_html/clients/mywebsite/vendor/mailchimp/mc-magento2/view/frontend/templates/form/newsletter.phtml(5): Ebizmarts\MailChimp\Block\Newsletter\Interceptor->getInterest()
#4 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/myserver...')
#5 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Ebizmarts\MailChimp\Block\Newsletter\Interceptor), '/home/myserver...', Array)
#6 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#7 /home/myserver/public_html/clients/mywebsite/vendor/mage2pro/core/Framework/Plugin/View/TemplateEngineInterface.php(21): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Ebizmarts\MailChimp\Block\Newsletter\Interceptor), '/home/myserver...', Array)
#8 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Df\Framework\Plugin\View\TemplateEngineInterface->aroundRender(Object(Magento\Framework\View\TemplateEngine\Php\Interceptor), Object(Closure), Object(Ebizmarts\MailChimp\Block\Newsletter\Interceptor), '/home/myserver...', Array)
#9 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Ebizmarts\MailChimp\Block\Newsletter\Interceptor), '/home/myserver...', Array)
#10 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(26): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins('render', Array, NULL)
#11 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php\Interceptor->render(Object(Ebizmarts\MailChimp\Block\Newsletter\Interceptor), '/home/myserver...', Array)
#12 /home/myserver/public_html/clients/mywebsite/generated/code/Ebizmarts/MailChimp/Block/Newsletter/Interceptor.php(128): Magento\Framework\View\Element\Template->fetchView('/home/myserver...')
#13 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Element/Template.php(300): Ebizmarts\MailChimp\Block\Newsletter\Interceptor->fetchView('/home/myserver...')
#14 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#15 /home/myserver/public_html/clients/mywebsite/generated/code/Ebizmarts/MailChimp/Block/Newsletter/Interceptor.php(453): Magento\Framework\View\Element\AbstractBlock->toHtml()
#16 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(558): Ebizmarts\MailChimp\Block\Newsletter\Interceptor->toHtml()
#17 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('customer.form.n...')
#18 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderNonCachedElement('customer.form.n...')
#19 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('renderNonCached...', Array)
#20 /home/myserver/public_html/clients/mywebsite/vendor/mage2pro/core/Framework/Plugin/View/Layout.php(166): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('customer.form.n...')
#21 /home/myserver/public_html/clients/mywebsite/generated/code/Df/Framework/Plugin/View/Layout/Interceptor.php(37): Df\Framework\Plugin\View\Layout->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'customer.form.n...')
#22 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Df\Framework\Plugin\View\Layout\Interceptor->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'customer.form.n...')
#23 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('customer.form.n...')
#24 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(208): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderNonCached...', Array, NULL)
#25 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('customer.form.n...')
#26 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('customer.form.n...', true)
#27 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('customer.form.n...', true)
#28 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Customer/Block/Newsletter/Interceptor.php(518): Magento\Framework\View\Element\AbstractBlock->getChildHtml('customer.form.n...', true)
#29 /home/myserver/public_html/clients/mywebsite/app/design/frontend/Mgs/claue/Magento_Customer/templates/form/newsletter.phtml(22): Magento\Customer\Block\Newsletter\Interceptor->getChildHtml('customer.form.n...')
#30 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/myserver...')
#31 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Customer\Block\Newsletter\Interceptor), '/home/myserver...', Array)
#32 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#33 /home/myserver/public_html/clients/mywebsite/vendor/mage2pro/core/Framework/Plugin/View/TemplateEngineInterface.php(21): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Customer\Block\Newsletter\Interceptor), '/home/myserver...', Array)
#34 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Df\Framework\Plugin\View\TemplateEngineInterface->aroundRender(Object(Magento\Framework\View\TemplateEngine\Php\Interceptor), Object(Closure), Object(Magento\Customer\Block\Newsletter\Interceptor), '/home/myserver...', Array)
#35 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Customer\Block\Newsletter\Interceptor), '/home/myserver...', Array)
#36 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(26): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins('render', Array, NULL)
#37 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php\Interceptor->render(Object(Magento\Customer\Block\Newsletter\Interceptor), '/home/myserver...', Array)
#38 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Customer/Block/Newsletter/Interceptor.php(284): Magento\Framework\View\Element\Template->fetchView('/home/myserver...')
#39 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Element/Template.php(300): Magento\Customer\Block\Newsletter\Interceptor->fetchView('/home/myserver...')
#40 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#41 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Customer/Block/Newsletter/Interceptor.php(609): Magento\Framework\View\Element\AbstractBlock->toHtml()
#42 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(558): Magento\Customer\Block\Newsletter\Interceptor->toHtml()
#43 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('customer_newsle...')
#44 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderNonCachedElement('customer_newsle...')
#45 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('renderNonCached...', Array)
#46 /home/myserver/public_html/clients/mywebsite/vendor/mage2pro/core/Framework/Plugin/View/Layout.php(166): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('customer_newsle...')
#47 /home/myserver/public_html/clients/mywebsite/generated/code/Df/Framework/Plugin/View/Layout/Interceptor.php(37): Df\Framework\Plugin\View\Layout->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'customer_newsle...')
#48 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Df\Framework\Plugin\View\Layout\Interceptor->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'customer_newsle...')
#49 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('customer_newsle...')
#50 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(208): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderNonCached...', Array, NULL)
#51 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('customer_newsle...')
#52 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('customer_newsle...', false)
#53 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('customer_newsle...', false)
#54 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content', false)
#55 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderNonCachedElement('content')
#56 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('renderNonCached...', Array)
#57 /home/myserver/public_html/clients/mywebsite/vendor/mage2pro/core/Framework/Plugin/View/Layout.php(166): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('content')
#58 /home/myserver/public_html/clients/mywebsite/generated/code/Df/Framework/Plugin/View/Layout/Interceptor.php(37): Df\Framework\Plugin\View\Layout->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'content')
#59 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Df\Framework\Plugin\View\Layout\Interceptor->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'content')
#60 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('content')
#61 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(208): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderNonCached...', Array, NULL)
#62 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#63 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', false)
#64 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('content', false)
#65 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main', false)
#66 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderNonCachedElement('main')
#67 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('renderNonCached...', Array)
#68 /home/myserver/public_html/clients/mywebsite/vendor/mage2pro/core/Framework/Plugin/View/Layout.php(166): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('main')
#69 /home/myserver/public_html/clients/mywebsite/generated/code/Df/Framework/Plugin/View/Layout/Interceptor.php(37): Df\Framework\Plugin\View\Layout->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'main')
#70 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Df\Framework\Plugin\View\Layout\Interceptor->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'main')
#71 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('main')
#72 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(208): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderNonCached...', Array, NULL)
#73 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#74 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', false)
#75 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('main', false)
#76 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('columns', false)
#77 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#78 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('renderNonCached...', Array)
#79 /home/myserver/public_html/clients/mywebsite/vendor/mage2pro/core/Framework/Plugin/View/Layout.php(166): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('columns')
#80 /home/myserver/public_html/clients/mywebsite/generated/code/Df/Framework/Plugin/View/Layout/Interceptor.php(37): Df\Framework\Plugin\View\Layout->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'columns')
#81 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Df\Framework\Plugin\View\Layout\Interceptor->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'columns')
#82 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('columns')
#83 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(208): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderNonCached...', Array, NULL)
#84 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#85 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', false)
#86 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('columns', false)
#87 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#88 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#89 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('renderNonCached...', Array)
#90 /home/myserver/public_html/clients/mywebsite/vendor/mage2pro/core/Framework/Plugin/View/Layout.php(166): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('main.content')
#91 /home/myserver/public_html/clients/mywebsite/generated/code/Df/Framework/Plugin/View/Layout/Interceptor.php(37): Df\Framework\Plugin\View\Layout->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'main.content')
#92 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Df\Framework\Plugin\View\Layout\Interceptor->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'main.content')
#93 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('main.content')
#94 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(208): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderNonCached...', Array, NULL)
#95 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#96 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', false)
#97 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('main.content', false)
#98 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#99 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#100 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('renderNonCached...', Array)
#101 /home/myserver/public_html/clients/mywebsite/vendor/mage2pro/core/Framework/Plugin/View/Layout.php(166): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('page.wrapper')
#102 /home/myserver/public_html/clients/mywebsite/generated/code/Df/Framework/Plugin/View/Layout/Interceptor.php(37): Df\Framework\Plugin\View\Layout->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'page.wrapper')
#103 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Df\Framework\Plugin\View\Layout\Interceptor->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'page.wrapper')
#104 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('page.wrapper')
#105 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(208): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderNonCached...', Array, NULL)
#106 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#107 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#108 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#109 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root', false)
#110 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderNonCachedElement('root')
#111 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('renderNonCached...', Array)
#112 /home/myserver/public_html/clients/mywebsite/vendor/mage2pro/core/Framework/Plugin/View/Layout.php(166): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('root')
#113 /home/myserver/public_html/clients/mywebsite/generated/code/Df/Framework/Plugin/View/Layout/Interceptor.php(37): Df\Framework\Plugin\View\Layout->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'root')
#114 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Df\Framework\Plugin\View\Layout\Interceptor->aroundRenderNonCachedElement(Object(Magento\Framework\View\Layout\Interceptor), Object(Closure), 'root')
#115 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}('root')
#116 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(208): Magento\Framework\View\Layout\Interceptor->___callPlugins('renderNonCached...', Array, NULL)
#117 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#118 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#119 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Layout.php(955): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#120 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#121 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#122 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#123 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#124 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#125 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#126 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#127 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): MGS\Mpanel\Block\Framework\Page\Interceptor->___callParent('renderResult', Array)
#128 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): MGS\Mpanel\Block\Framework\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#129 /home/myserver/public_html/clients/mywebsite/generated/code/MGS/Mpanel/Block/Framework/Page/Interceptor.php(156): MGS\Mpanel\Block\Framework\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#130 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/App/View.php(221): MGS\Mpanel\Block\Framework\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#131 /home/myserver/public_html/clients/mywebsite/vendor/magento/module-newsletter/Controller/Manage/Index.php(24): Magento\Framework\App\View->renderLayout()
#132 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Newsletter\Controller\Manage\Index->execute()
#133 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Newsletter\Controller\Manage\Index\Interceptor->___callParent('execute', Array)
#134 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Newsletter\Controller\Manage\Index\Interceptor->Magento\Framework\Interception\{closure}()
#135 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Newsletter/Controller/Manage/Index/Interceptor.php(26): Magento\Newsletter\Controller\Manage\Index\Interceptor->___callPlugins('execute', Array, Array)
#136 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/App/Action/Action.php(107): Magento\Newsletter\Controller\Manage\Index\Interceptor->execute()
#137 /home/myserver/public_html/clients/mywebsite/vendor/magento/module-newsletter/Controller/Manage.php(45): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#138 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Newsletter\Controller\Manage->dispatch(Object(Magento\Framework\App\Request\Http))
#139 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Newsletter\Controller\Manage\Index\Interceptor->___callParent('dispatch', Array)
#140 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Newsletter\Controller\Manage\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#141 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Newsletter/Controller/Manage/Index/Interceptor.php(39): Magento\Newsletter\Controller\Manage\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#142 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/App/FrontController.php(55): Magento\Newsletter\Controller\Manage\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#143 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#144 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#145 /home/myserver/public_html/clients/mywebsite/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#146 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#147 /home/myserver/public_html/clients/mywebsite/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#148 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#149 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#150 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#151 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#152 /home/myserver/public_html/clients/mywebsite/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#153 /home/myserver/public_html/clients/mywebsite/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#154 /home/myserver/public_html/clients/mywebsite/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#155 {main}
```

### Preconditions

    1. Magento CE 2.2.5
    2. mc-magento2 1.0.21.
    3. Logged in customer in frontend

### Steps to reproduce

    1. Navigate to storefront as a logged in customer.
    2. Go to 'My account' page
    3. Click "My Newsletter Subscriptions" on the customer account sidebar menu.

**Comment by SantiParagarino** [comment]
Hello @ktsixit 

Please update to the latest error for Magento 2.2. (Currently 101.2.34)
That should solve your problem.

In case the error persist we can reopen this issue.

Kind Regards.
