### ISSUE TITLE
Uncaught Error: Call to a member function count() on null

### ISSUE THREAD

**Issue by dodiya-divyarajsinh** [mailchimp/mc-magento2#691]
### Preconditions

I have Magento ver. 2.1.6 on our live site.

Example:

    1. Magento CE 2.1.6 without sample data is installed we have our own products.
    2. Ebizmarts_MailChimp 1.0.27
    ...

### Steps to reproduce

When user registered, Place order, or Newsletter subscription not any email is come to user email address. When we check in log file it will show below contenst. 

Example:

    1. Navigate to storefront as a guest/login.
    2. Open Any Category.
    3. Click "Add to Cart" on the Product.
    4. Open mini shopping cart and click "Proceed to Checkout".
    5. Try to place and Order.
    ...

### Actual and Expected result

Email come to user account using MailChimp.

### Additional information

Log file content

```
PHP Fatal error:  Uncaught Error: Call to a member function count() on null in /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php:191
Stack trace:
#0 /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php(94): Ebizmarts\MailChimp\Cron\Webhook->_profile(Array)
#1 /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php(65): Ebizmarts\MailChimp\Cron\Webhook->processWebhooks()
#2 [internal function]: Ebizmarts\MailChimp\Cron\Webhook->execute(Object(Magento\Cron\Model\Schedule))
#3 /public_html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(247): call_user_func_array(Array, Array)
#4 /public_html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(195): Magento\Cron\Observer\ProcessCronQueueObserver->_runJob(1556299800, 1556299803, Array, Object(Magento\Cron\Model\Schedule), 'default') in /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php on line 191
PHP Fatal error:  Uncaught Error: Call to a member function count() on null in /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php:191
Stack trace:
#0 /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php(94): Ebizmarts\MailChimp\Cron\Webhook->_profile(Array)
#1 /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php(65): Ebizmarts\MailChimp\Cron\Webhook->processWebhooks()
#2 [internal function]: Ebizmarts\MailChimp\Cron\Webhook->execute(Object(Magento\Cron\Model\Schedule))
#3 /public_html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(247): call_user_func_array(Array, Array)
#4 /public_html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(195): Magento\Cron\Observer\ProcessCronQueueObserver->_runJob(1556300700, 1556300702, Array, Object(Magento\Cron\Model\Schedule), 'default') in /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php on line 191
PHP Fatal error:  Uncaught Error: Call to a member function count() on null in /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php:191
Stack trace:
#0 /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php(94): Ebizmarts\MailChimp\Cron\Webhook->_profile(Array)
#1 /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php(65): Ebizmarts\MailChimp\Cron\Webhook->processWebhooks()
#2 [internal function]: Ebizmarts\MailChimp\Cron\Webhook->execute(Object(Magento\Cron\Model\Schedule))
#3 /public_html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(247): call_user_func_array(Array, Array)
#4 /public_html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(195): Magento\Cron\Observer\ProcessCronQueueObserver->_runJob(1556301600, 1556301604, Array, Object(Magento\Cron\Model\Schedule), 'default') in /public_html/app/code/Ebizmarts/MailChimp/Cron/Webhook.php on line 191

```

**Comment by gonzaloebiz** [comment]
Please follow the issue format

**Comment by dodiya-divyarajsinh** [comment]
@gonzaloebiz  I have update issue comment.

**Comment by gonzaloebiz** [comment]
If you have mc-magento2 1.0.27 please update it to the current version

Best
